<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0;net10.0-windows</TargetFrameworks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Examples.fs" />
    <ProjectReference Include="../../src/Xanthos/Xanthos.fsproj" />
  </ItemGroup>
</Project>
